### ISSUE TITLE
Can't build rpm package

### ISSUE THREAD

**Issue by nit-in** [mer-hybris/qt5-qpa-surfaceflinger-plugin#2]
I have tried building it alone also
But it is giving me this error again and again
```
`/srv/mer/toolings/xiaomi-beryllium-armv7hl/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: /srv/mer/targets/xiaomi-beryllium-armv7hl/usr/lib/libQt5PlatformSupport.a(qeventdispatcher_glib.o): in function `QPAEventDispatcherGlibPrivate::QPAEventDispatcherGlibPrivate(_GMainContext*)':
(.text+0x48): undefined reference to `g_source_new'
/srv/mer/toolings/xiaomi-beryllium-armv7hl/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: (.text+0x52): undefined reference to `g_source_set_can_recurse'
/srv/mer/toolings/xiaomi-beryllium-armv7hl/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: (.text+0x5a): undefined reference to `g_source_attach'
/srv/mer/toolings/xiaomi-beryllium-armv7hl/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: /srv/mer/targets/xiaomi-beryllium-armv7hl/usr/lib/libQt5PlatformSupport.a(qeventdispatcher_glib.o): in function `QPAEventDispatcherGlib::~QPAEventDispatcherGlib()':
(.text+0xc4): undefined reference to `g_source_destroy'
/srv/mer/toolings/xiaomi-beryllium-armv7hl/opt/cross/bin/armv7hl-meego-linux-gnueabi-ld: (.text+0xca): undefined reference to `g_source_unref'
collect2: error: ld returned 1 exit status
make: *** [Makefile:100: plugins/platforms/libsurfaceflinger.so] Error 1`
```

I can't understand what is wrong here.
Is this a problem with compiler or with glib?
I have tried entering glib2 path manually in .pro file
but same thing

**Comment by rburchell** [comment]
It's hard to tell what is going on without all the details, but some possibilities I'd see off the top of my head:

* It (glib) isn't being linked in the link command, despite being used by something else that *is* being linked: something may be wrong with the .pro.
* Linking against it (glib) is attempted, but the library is incompatible (wrong architecture, or whatever) -- you'd likely see another message somewhere in the output about this: something may be wrong with the build environment.
* Linking against it (glib) is attempted, and this stuff is the only message you get: those symbols may not be present in the glib that is being linked (for whatever reason): something may be wrong with the glib library, or build environment.

I'd first start by checking that glib is present in the link command. If it is, then check the architecture and symbols in the library that it is linking.

**Comment by nit-in** [comment]
More details
PLATFORM_SDK_ROOT=/srv/mer
PLATFORM_SDK=http://releases.sailfishos.org/sdk/installers/latest/Jolla-latest-SailfishOS_Platform_SDK_Chroot-i486.tar.bz2
sfossdk commond works
Ubuntu-chroot also works
Successfully compiled hybris-boot and hybris-recovery image(LineageOS as base)
Set up the sb2
I changed the names so my folders look like this
/srv/mer/target/xiaomi-beryllium_armv7hl and /srv/mer/tooling/xiaomi-beryllium_armv7hl
for target I used

sdk-assistant tooling create $VENDOR-$DEVICE-$PORT_ARCH https://releases.sailfishos.org/sdk/targets/Sailfish_OS-latest-Sailfish_SDK_Tooling-i486.tar.7z

sdk-assistant target create $VENDOR-$DEVICE-$PORT_ARCH https://releases.sailfishos.org/sdk/targets/Sailfish_OS-latest-Sailfish_SDK_Target-armv7hl.tar.7z

and it passed the "hello world" test program given in porting guide

I am at building droid hal
PLATFORM_SDK $
cd $ANDROID_ROOT
rpm/dhd/helpers/build_packages.sh

It fails

I tried installing it alone
rpm/dhd/helpers/build_packages.sh -b qt5-qpa-surfaceflinger-plugin
here is the error log: https://pastebin.com/PUC5szCF

other than modifying the .pro file
I also tried reinstalling glib2 with zypper in platform_sdk
Didn't help also

**Comment by nit-in** [comment]
I solved the problem by adding QMAKE_PRL_LIBS = -lglib-2.0

in srv/mer/targets/mydevice/usr/lib/libQt5PlatformSupport.prl

**Comment by sledges** [comment]
Just to inform you, qt5-qpa-hwcomposer-plugin plugin should be used instead of this surfaceflinger plugin.
This surfaceflinger plugin could only be of help when a new version of HWC comes out and the qpa hwc plugin lacks its support or does not fallback to a lower version. However this and libsurfaceflinger_compat_layer projects are currently not maintained.

At the time of writing, qt5-qpa-hwcomposer-plugin supports or falls-back to all known HWC versions.

In mer-hybris adaptations it's being removed from the standard build queue: https://github.com/mer-hybris/droid-hal-device/pull/234

**Comment by nit-in** [comment]
oh Thank you
I will pay attention to this next
I did manage to build sailfishOS package for my device and flashed it after lineage rom
Tar was giving me grief
So I downgraded my recovery and flashed the rom without any problem
Though device was stuck on bootloop
The problem is I can't debug it
I can't telnet into device
As in my host dmesg Manufacturer shows up as google instead of Mer bootloader
I wanted some help
I did mail David Greaves for a username on for mer.project.org
so I can ask for help
But Still haven't gotten any reply from him

**Comment by mlehtima** [comment]
If you are looking for help with porting Sailfish OS for a device then you should join #sailfishos-porters Freenode IRC channel.

**Comment by nit-in** [comment]
ok 👍
